#log配置
logging:
  path: E:\\log\\mas
  level:
    root: info

spring:
  #dubbo配置
  dubbo:
    application:
      id: app-party-id
      name: iaa-app-party-service
    server: true
    registry:
      address: zookeeper://localhost:2181
      port: 2181
    protocol:
      name: dubbo
      port: 20891
      threads: 10
    scan: com.huazai.livehouse.wechat.subscription.platform.service.impl